version: "3"
services:
  node:
    build: .
    command: sleep infinity
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ~/Library/Caches/Yarn/v4:/usr/local/share/.cache/yarn/v4
      - firebase_example_sync:/app
    environment:
      SHELL: "/bin/bash"
      HOME: "/root"
    ports:
      - "127.0.0.1:9898:3000"
volumes:
  firebase_example_sync:
    external: true
